#??????
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8990/eureka/
  instance:
    prefer-ip-address: true
#?????
server:
  port: 8991

spring:
  #?? boot 2.0 ?????????????????jsonFormat??????
  jackson:
    serialization:
      write-dates-as-timestamps: true
  application:
    name: farm-main  #??????
    #??????????
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/farm?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

config:
  root-url: /farm_main/api/v1/
  land-contract: '0x7EB5F588631e40fea7c65ec5eF5a438105b452E6'
  pond-contract: ''
  transactionUrl: 'https://api-testnet.bscscan.com/api?module=account&action=tokennfttx&contractaddress=%s&address=%s&page=1&offset=100&sort=asc'


